apiVersion: cache.yazio.com/v1alpha1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: yazio-challenge
    app.kubernetes.io/managed-by: kustomize
  name: redis-sample
spec:
  # TODO(user): Add fields here
